import "./globals.css";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/providers/theme-provider";
import { playfair } from "@/styles/fonts";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-back text-fore dark:bg-back-dark/50 dark:text-fore-dark",
          playfair.className,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
