export const hero_carousel_slides = [
  {
    id: 1,
    height: 1175,
    width: 1600,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-zT6c5Y-IJOX5X27B1Gx7FmgKJVqp-E_ty_eF8bGNGgu5W9_kWP1Hf9kObXfMDf0_eBhraOzT8aEQ78DxRIwoXPjD30HQ=w1600",
    alt: "front_desk",
    subtitle: "front_desk",
    description: "front_desk",
  },
  {
    id: 2,
    height: 1067,
    width: 1600,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-w95w6w93fvkjFv7r6XbOVqXsaSKZjVVN9-tXpAeiToDkGuJjnoPFKFLmce8SNV_CyHW5meGjjVIVxefPdU7ZATFCnDcg=w1600",
    alt: "lobby_a",
    subtitle: "lobby_a",
    description: "lobby_a",
  },
  {
    id: 3,
    height: 1245,
    width: 1600,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-wWDRWGTzthhMEjN_pThwZOyBSTy6yLIYuyi0kcjGLi_Tnh7ZVjrqK_H4TUHDZQdx1e3RSDpIoBJegmcQLKOH4TUvgkog=w1600",
    alt: "lobby_b",
    subtitle: "lobby_b",
    description: "lobby_b",
  },
  {
    id: 4,
    height: 980,
    width: 1600,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-ylowQDpH7_GQwvi-jZcjlyGJ8Dt7h-j-DfOOJyTyrwTYpIx2nQbvkovmsJEgqJQ7a0x_i1mTnujWvMpAgi3-t8YWQtwQ=w1600",
    alt: "restaurant_a",
    subtitle: "restaurant_a",
    description: "restaurant_a",
  },
  {
    id: 5,
    height: 975,
    width: 1600,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-wVHvEdw9iJbfVQ6vfYOEd0iPXIZq-ennlAziyv4IAohsEPBTxuOmIsmvLDLQPMdtO0aInCiqNbQIXEQKD8cEy9XLNQBA=w1600",
    alt: "restaurant_b",
    subtitle: "restaurant_b",
    description: "restaurant_b",
  },
  {
    id: 6,
    height: 1067,
    width: 1600,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-zzFUq2URNTrI_o7jr5LUUljHM8-3ixBWqW0ShpyKsdQr3myip-mGXB3IUhlK9yWUXzbrDEiQgLpuOHHhg7xg91UN7V=w1600",
    alt: "building_front",
    subtitle: "building_front",
    description: "building_front",
  },
  {
    id: 7,
    height: 1200,
    width: 1920,
    src: "https://lh3.googleusercontent.com/drive-viewer/AITFw-wVAWvZeFHP3uivaIQDP7HeSoPLtYMElNf8i0eVqxDOFXaLIFz6xungi9sNVfLRTQhbDIjD7u08OU9CQCWxI0VTqym45w=w1920",
    alt: "grid",
    subtitle: "grid",
    description: "grid",
  },
];
