INSERT INTO
  room_types (name)
VALUES
  ('Deluxe'),
  ('Executive'),
  ('Twin'),
  ('Family');

INSERT INTO
  rooms (id, room_type_id)
VALUES
  (101, 1), (102, 1), (103, 2), (104, 1), (105, 1), (106, 2), (107, 1), (108, 1),
  (201, 1), (202, 1), (203, 3), (204, 3), (205, 1), (206, 3), (207, 1), (208, 1),
  (301, 1), (302, 1), (303, 2), (304, 3), (305, 1), (306, 2), (307, 1), (308, 1),
  (401, 4), (402, 4), (403, 2), (404, 1), (405, 1), (406, 2),
  (501, 4), (502, 4), (503, 2), (504, 1), (505, 1), (506, 2);

INSERT INTO
  public.customers(name, nationality)
VALUES
  ('Carlos Sainz', 'Spain'),
  ('Charles Leclerc', 'Monaco'),
  ('Daniel Riccardo', 'Australia'),
  ('Fernando Alonso', 'Spain'),
  ('Kimi Raikkonen', 'Finland'),
  ('Lando Norris', 'UK'),
  ('Lewis Hamilton', 'UK'),
  ('Max Verstappen', 'Netherlands'),

INSERT INTO
  reservations(
    room_id,
    customer_id,
    room_rate,
    check_in,
    check_out,
    source,
    status
  )
VALUES 
  (101, 1, 3000, '2023-09-01 12:00', '2023-09-020 12:00', 'expedia.com', 'booked'),
  (102, 2, 3000, '2023-09-03 12:00', '2023-09-015 12:00', 'booking.com', 'booked'),
  (103, 3, 3000, '2023-09-09 12:00', '2023-09-023 12:00', 'corporate', 'booked');

INSERT INTO
  countries(id, iso, iso3, name)
values
(1, 'AF', 'AFG', 'Afghanistan'),
(2, 'AL', 'ALB', 'Albania'),
(3, 'DZ', 'DZA', 'Algeria'),
(4, 'AS', 'ASM', 'American Samoa'),
(5, 'AD', 'AND', 'Andorra'),
(6, 'AO', 'AGO', 'Angola'),
(7, 'AI', 'AIA', 'Anguilla'),
(8, 'AQ', NULL, 'Antarctica'),
(9, 'AG', 'ATG', 'Antigua and Barbuda'),
(10, 'AR', 'ARG', 'Argentina'),
(11, 'AM', 'ARM', 'Armenia'),
(12, 'AW', 'ABW', 'Aruba'),
(13, 'AU', 'AUS', 'Australia'),
(14, 'AT', 'AUT', 'Austria'),
(15, 'AZ', 'AZE', 'Azerbaijan'),
(16, 'BS', 'BHS', 'Bahamas'),
(17, 'BH', 'BHR', 'Bahrain'),
(18, 'BD', 'BGD', 'Bangladesh'),
(19, 'BB', 'BRB', 'Barbados'),
(20, 'BY', 'BLR', 'Belarus'),
(21, 'BE', 'BEL', 'Belgium'),
(22, 'BZ', 'BLZ', 'Belize'),
(23, 'BJ', 'BEN', 'Benin'),
(24, 'BM', 'BMU', 'Bermuda'),
(25, 'BT', 'BTN', 'Bhutan'),
(26, 'BO', 'BOL', 'Bolivia'),
(27, 'BA', 'BIH', 'Bosnia and Herzegovina'),
(28, 'BW', 'BWA', 'Botswana'),
(29, 'BV', NULL, 'Bouvet Island'),
(30, 'BR', 'BRA', 'Brazil'),
(31, 'IO', NULL, 'British Indian Ocean Territory'),
(32, 'BN', 'BRN', 'Brunei Darussalam'),
(33, 'BG', 'BGR', 'Bulgaria'),
(34, 'BF', 'BFA', 'Burkina Faso'),
(35, 'BI', 'BDI', 'Burundi'),
(36, 'KH', 'KHM', 'Cambodia'),
(37, 'CM', 'CMR', 'Cameroon'),
(38, 'CA', 'CAN', 'Canada'),
(39, 'CV', 'CPV', 'Cape Verde'),
(40, 'KY', 'CYM', 'Cayman Islands'),
(41, 'CF', 'CAF', 'Central African Republic'),
(42, 'TD', 'TCD', 'Chad'),
(43, 'CL', 'CHL', 'Chile'),
(44, 'CN', 'CHN', 'China'),
(45, 'CX', NULL, 'Christmas Island'),
(46, 'CC', NULL, 'Cocos (Keeling) Islands'),
(47, 'CO', 'COL', 'Colombia'),
(48, 'KM', 'COM', 'Comoros'),
(49, 'CG', 'COG', 'Congo'),
(50, 'CD', 'COD', 'Congo, the Democratic Republic of the'),
(51, 'CK', 'COK', 'Cook Islands'),
(52, 'CR', 'CRI', 'Costa Rica'),
(53, 'CI', 'CIV', E 'Cote D\'Ivoire'),
(54, 'HR', 'HRV', 'Croatia'),
(55, 'CU', 'CUB', 'Cuba'),
(56, 'CY', 'CYP', 'Cyprus'),
(57, 'CZ', 'CZE', 'Czech Republic'),
(58, 'DK', 'DNK', 'Denmark'),
(59, 'DJ', 'DJI', 'Djibouti'),
(60, 'DM', 'DMA', 'Dominica'),
(61, 'DO', 'DOM', 'Dominican Republic'),
(62, 'EC', 'ECU', 'Ecuador'),
(63, 'EG', 'EGY', 'Egypt'),
(64, 'SV', 'SLV', 'El Salvador'),
(65, 'GQ', 'GNQ', 'Equatorial Guinea'),
(66, 'ER', 'ERI', 'Eritrea'),
(67, 'EE', 'EST', 'Estonia'),
(68, 'ET', 'ETH', 'Ethiopia'),
(69, 'FK', 'FLK', 'Falkland Islands'),
(70, 'FO', 'FRO', 'Faroe Islands'),
(71, 'FJ', 'FJI', 'Fiji'),
(72, 'FI', 'FIN', 'Finland'),
(73, 'FR', 'FRA', 'France'),
(74, 'GF', 'GUF', 'French Guiana'),
(75, 'PF', 'PYF', 'French Polynesia'),
(76, 'TF', NULL, 'French Southern Territories'),
(77, 'GA', 'GAB', 'Gabon'),
(78, 'GM', 'GMB', 'Gambia'),
(79, 'GE', 'GEO', 'Georgia'),
(80, 'DE', 'DEU', 'Germany'),
(81, 'GH', 'GHA', 'Ghana'),
(82, 'GI', 'GIB', 'Gibraltar'),
(83, 'GR', 'GRC', 'Greece'),
(84, 'GL', 'GRL', 'Greenland'),
(85, 'GD', 'GRD', 'Grenada'),
(86, 'GP', 'GLP', 'Guadeloupe'),
(87, 'GU', 'GUM', 'Guam'),
(88, 'GT', 'GTM', 'Guatemala'),
(89, 'GN', 'GIN', 'Guinea'),
(90, 'GW', 'GNB', 'Guinea-Bissau'),
(91, 'GY', 'GUY', 'Guyana'),
(92, 'HT', 'HTI', 'Haiti'),
(93, 'HM', NULL, 'Heard Island and Mcdonald Islands'),
(94, 'VA', 'VAT', 'Vatican City'),
(95, 'HN', 'HND', 'Honduras'),
(96, 'HK', 'HKG', 'Hong Kong'),
(97, 'HU', 'HUN', 'Hungary'),
(98, 'IS', 'ISL', 'Iceland'),
(99, 'IN', 'IND', 'India'),
(100, 'ID', 'IDN', 'Indonesia'),
(101, 'IR', 'IRN', 'Iran'),
(102, 'IQ', 'IRQ', 'Iraq'),
(103, 'IE', 'IRL', 'Ireland'),
(104, 'IL', 'ISR', 'Israel'),
(105, 'IT', 'ITA', 'Italy'),
(106, 'JM', 'JAM', 'Jamaica'),
(107, 'JP', 'JPN', 'Japan'),
(108, 'JO', 'JOR', 'Jordan'),
(109, 'KZ', 'KAZ', 'Kazakhstan'),
(110, 'KE', 'KEN', 'Kenya'),
(111, 'KI', 'KIR', 'Kiribati'),
(112, 'KP', 'PRK', 'North Korea'),
(113, 'KR', 'KOR', 'South Korea'),
(114, 'KW', 'KWT', 'Kuwait'),
(115, 'KG', 'KGZ', 'Kyrgyzstan'),
(116, 'LA', 'LAO', 'Laos'),
(117, 'LV', 'LVA', 'Latvia'),
(118, 'LB', 'LBN', 'Lebanon'),
(119, 'LS', 'LSO', 'Lesotho'),
(120, 'LR', 'LBR', 'Liberia'),
(121, 'LY', 'LBY', 'Libya'),
(122, 'LI', 'LIE', 'Liechtenstein'),
(123, 'LT', 'LTU', 'Lithuania'),
(124, 'LU', 'LUX', 'Luxembourg'),
(125, 'MO', 'MAC', 'Macao'),
(126, 'MK', 'MKD', 'Macedonia'),
(127, 'MG', 'MDG', 'Madagascar'),
(128, 'MW', 'MWI', 'Malawi'),
(129, 'MY', 'MYS', 'Malaysia'),
(130, 'MV', 'MDV', 'Maldives'),
(131, 'ML', 'MLI', 'Mali'),
(132, 'MT', 'MLT', 'Malta'),
(133, 'MH', 'MHL', 'Marshall Islands'),
(134, 'MQ', 'MTQ', 'Martinique'),
(135, 'MR', 'MRT', 'Mauritania'),
(136, 'MU', 'MUS', 'Mauritius'),
(137, 'YT', NULL, 'Mayotte'),
(138, 'MX', 'MEX', 'Mexico'),
(139, 'FM', 'FSM', 'Micronesia'),
(140, 'MD', 'MDA', 'Moldova'),
(141, 'MC', 'MCO', 'Monaco'),
(142, 'MN', 'MNG', 'Mongolia'),
(143, 'MS', 'MSR', 'Montserrat'),
(144, 'MA', 'MAR', 'Morocco'),
(145, 'MZ', 'MOZ', 'Mozambique'),
(146, 'MM', 'MMR', 'Myanmar'),
(147, 'NA', 'NAM', 'Namibia'),
(148, 'NR', 'NRU', 'Nauru'),
(149, 'NP', 'NPL', 'Nepal'),
(150, 'NL', 'NLD', 'Netherlands'),
(151, 'AN', 'ANT', 'Netherlands Antilles'),
(152, 'NC', 'NCL', 'New Caledonia'),
(153, 'NZ', 'NZL', 'New Zealand'),
(154, 'NI', 'NIC', 'Nicaragua'),
(155, 'NE', 'NER', 'Niger'),
(156, 'NG', 'NGA', 'Nigeria'),
(157, 'NU', 'NIU', 'Niue'),
(158, 'NF', 'NFK', 'Norfolk Island'),
(159, 'MP', 'MNP', 'Northern Mariana Islands'),
(160, 'NO', 'NOR', 'Norway'),
(161, 'OM', 'OMN', 'Oman'),
(162, 'PK', 'PAK', 'Pakistan'),
(163, 'PW', 'PLW', 'Palau'),
(164, 'PS', NULL, 'Palestinian Territory'),
(165, 'PA', 'PAN', 'Panama'),
(166, 'PG', 'PNG', 'Papua New Guinea'),
(167, 'PY', 'PRY', 'Paraguay'),
(168, 'PE', 'PER', 'Peru'),
(169, 'PH', 'PHL', 'Philippines'),
(170, 'PN', 'PCN', 'Pitcairn'),
(171, 'PL', 'POL', 'Poland'),
(172, 'PT', 'PRT', 'Portugal'),
(173, 'PR', 'PRI', 'Puerto Rico'),
(174, 'QA', 'QAT', 'Qatar'),
(175, 'RE', 'REU', 'Reunion'),
(176, 'RO', 'ROM', 'Romania'),
(177, 'RU', 'RUS', 'Russian Federation'),
(178, 'RW', 'RWA', 'Rwanda'),
(179, 'SH', 'SHN', 'Saint Helena'),
(180, 'KN', 'KNA', 'Saint Kitts and Nevis'),
(181, 'LC', 'LCA', 'Saint Lucia'),
(182, 'PM', 'SPM', 'Saint Pierre and Miquelon'),
(183, 'VC', 'VCT', 'Saint Vincent and the Grenadines'),
(184, 'WS', 'WSM', 'Samoa'),
(185, 'SM', 'SMR', 'San Marino'),
(186, 'ST', 'STP', 'Sao Tome and Principe'),
(187, 'SA', 'SAU', 'Saudi Arabia'),
(188, 'SN', 'SEN', 'Senegal'),
(189, 'CS', NULL, 'Serbia and Montenegro'),
(190, 'SC', 'SYC', 'Seychelles'),
(191, 'SL', 'SLE', 'Sierra Leone'),
(192, 'SG', 'SGP', 'Singapore'),
(193, 'SK', 'SVK', 'Slovakia'),
(194, 'SI', 'SVN', 'Slovenia'),
(195, 'SB', 'SLB', 'Solomon Islands'),
(196, 'SO', 'SOM', 'Somalia'),
(197, 'ZA', 'ZAF', 'South Africa'),
(198, 'GS', NULL, 'South Georgia and the South Sandwich Islands'),
(199, 'ES', 'ESP', 'Spain'),
(200, 'LK', 'LKA', 'Sri Lanka'),
(201, 'SD', 'SDN', 'Sudan'),
(202, 'SR', 'SUR', 'Suriname'),
(203, 'SJ', 'SJM', 'Svalbard and Jan Mayen'),
(204, 'SZ', 'SWZ', 'Swaziland'),
(205, 'SE', 'SWE', 'Sweden'),
(206, 'CH', 'CHE', 'Switzerland'),
(207, 'SY', 'SYR', 'Syrian Arab Republic'),
(208, 'TW', 'TWN', 'Taiwan'),
(209, 'TJ', 'TJK', 'Tajikistan'),
(210, 'TZ', 'TZA', 'Tanzania, United Republic of'),
(211, 'TH', 'THA', 'Thailand'),
(212, 'TL', NULL, 'Timor-Leste'),
(213, 'TG', 'TGO', 'Togo'),
(214, 'TK', 'TKL', 'Tokelau'),
(215, 'TO', 'TON', 'Tonga'),
(216, 'TT', 'TTO', 'Trinidad and Tobago'),
(217, 'TN', 'TUN', 'Tunisia'),
(218, 'TR', 'TUR', 'Turkey'),
(219, 'TM', 'TKM', 'Turkmenistan'),
(220, 'TC', 'TCA', 'Turks and Caicos Islands'),
(221, 'TV', 'TUV', 'Tuvalu'),
(222, 'UG', 'UGA', 'Uganda'),
(223, 'UA', 'UKR', 'Ukraine'),
(224, 'AE', 'ARE', 'United Arab Emirates'),
(225, 'GB', 'GBR', 'United Kingdom'),
(226, 'US', 'USA', 'United States'),
(227, 'UM', NULL, 'United States Minor Outlying Islands'),
(228, 'UY', 'URY', 'Uruguay'),
(229, 'UZ', 'UZB', 'Uzbekistan'),
(230, 'VU', 'VUT', 'Vanuatu'),
(231, 'VE', 'VEN', 'Venezuela'),
(232, 'VN', 'VNM', 'Viet Nam'),
(233, 'VG', 'VGB', 'Virgin Islands, British'),
(234, 'VI', 'VIR', 'Virgin Islands, U.S.'),
(235, 'WF', 'WLF', 'Wallis and Futuna'),
(236, 'EH', 'ESH', 'Western Sahara'),
(237, 'YE', 'YEM', 'Yemen'),
(238, 'ZM', 'ZMB', 'Zambia'),
(239, 'ZW', 'ZWE', 'Zimbabwe');